---
title: Patrick Sellers
author: Pat Sellers
date: '2018-01-18'
slug: \\2018-01-18-cv
categories:
  - R
tags: []
---

pasellers11@gmail.com  
Davidson, NC  
https://www.linkedin.com/in/patrickjsellers/  
704-284-3503 

# EXECUTIVE PROFILE
Senior innovation and analytics leader. Experienced and creative leader in higher education, inspiring and implementing data driven decision-making and change across all parts of an organization. Creative use of data and technology to advance organizational goals. Deep expertise in quantitative and qualitative research and assessment. Demonstrated success in building, leading, and teaching research teams, and communicating research results to mobilize coalitions of diverse constituencies for change. Strong social and communication skills.

# PROFESSIONAL EXPERIENCE

## DAVIDSON COLLEGE, Davidson, NC (2000 - present)
* ### Vice President for Strategic Partnerships (2014-present)
     + Innovations around data and technology
          - Led faculty initiatives to develop minors in Data Science (which incorporated courses and faculty in departments from Biology and Computer Science to History and Art), and in Digital Studies (which brought together faculty from all humanities departments).
          - Managed partnerships to create online courses on topics from genomics and AP microeconomics to voting fraud and redistricting. Led fundraising efforts that secured $2.8MM in foundation funding to create courses. Identified key talent, and created consensus around making an opportunity hire to bring in needed leadership. 

